POST http://localhost:3001/tasks
Content-Type: application/json

{
    "title": "Title of the Task Seven",
    "dueDate": "2025-01-01T12:00:00Z",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    "priority": "",
    "status": ""
}